version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgresql
      - rabbitmq
      - redis
    volumes:
      - ./web/app/static:/usr/src/app/static
    command: /usr/local/bin/gunicorn -w 2 -b :8000 wsgi:app
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - BYTARDAG_CONFIG=${BYTARDAG_CONFIG}
      - BYTARDAG_ADMIN=${BYTARDAG_ADMIN}
      - DATABASE_URI=${DATABASE_URI}
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  postgresql:
    restart: always
    build: ./postgres
    expose:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    restart: always
    image: redis
    expose:
      - "6379"

  rabbitmq:
    restart: always
    image: rabbitmq:3
    expose:
      - "5672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  worker:
    build: ./web
    links:
      - postgresql
      - rabbitmq
      - redis
    volumes:
      - /usr/src/app/static
    command: celery -A app.celery worker
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - BYTARDAG_CONFIG=${BYTARDAG_CELERY_CONFIG}
      - BYTARDAG_ADMIN=${BYTARDAG_ADMIN}
      - CELERY_DATABASE_URI=${DATABASE_URI}
      - BROKER_URL=${BROKER_URL}
      - RESULT_BACKEND=${RESULT_BACKEND}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

volumes:
  dbdata:
    driver: local
