"""Added attributes to User.

Revision ID: 8ce5e5684e57
Revises: 76f2b3e733ab
Create Date: 2016-08-22 19:52:49.906327

"""

# revision identifiers, used by Alembic.
revision = '8ce5e5684e57'
down_revision = '76f2b3e733ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
