"""Added field for GDPR status.

Revision ID: acd29f303bfb
Revises: 0c0c2110ae8b
Create Date: 2018-09-08 17:59:31.504114

"""

# revision identifiers, used by Alembic.
revision = 'acd29f303bfb'
down_revision = '0c0c2110ae8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gdpr_consent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gdpr_consent')
    # ### end Alembic commands ###
