"""Added attribute for generating seller ids

Revision ID: bc1d6194ff58
Revises: f5dfc7172ff5
Create Date: 2016-09-03 16:34:02.824641

"""

# revision identifiers, used by Alembic.
revision = 'bc1d6194ff58'
down_revision = 'f5dfc7172ff5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('next_seller_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'next_seller_id')
    ### end Alembic commands ###
