"""Working association object

Revision ID: f5dfc7172ff5
Revises: 1c3642736709
Create Date: 2016-08-26 21:47:40.081690

"""

# revision identifiers, used by Alembic.
revision = 'f5dfc7172ff5'
down_revision = '1c3642736709'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('seller_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.drop_table('events_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='events_users_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='events_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name='events_users_pkey')
    )
    op.drop_table('attendance')
    ### end Alembic commands ###
